Algoritmo "operadora"



Var

   minu,minP: real
   valorPlano,ValorMul: real




Inicio

      escreval ("Digite a quantidade de minutos: ")
      leia (minu)

      valorPlano <- 50

      se minu <= 100 entao
         escreval ("Valor a pagar: R$",ValorPlano)
      senao
      Minp <- minu - 100
      ValorMul <- Minp * 2 + ValorPlano
               escreval("Valor a pagar: R$",ValorMul:3:2)
   fimse


Fimalgoritmo