Algoritmo "soma"

Var
   x,y,soma: real
Inicio
      escreval ("***********")
      escreval ("Função Soma")
      escreval ("***********")
      escreval()
      
      escreval("Digite o valor de X: ")
      leia (x)
      escreval ("Digite o valor de Y: ")
      leia (y)
      
      soma <- x + y
      
      escreval ()
      escreval ("A soma de",x," +",y," é:",soma)
      
      


Fimalgoritmo