Algoritmo "combustivel"

Var
     distancia, comb, media: real


Inicio
      escreval("**********************")
      escreval("CONSUMO DE COMBUSTÍVEL")
      escreval("**********************")
      escreval ("")

      escreval ("Digite a distância percorrida: ")
      leia (distancia)
      escreval ("Digite a quantidade combustível em L: ")
      leia (comb)
      
      media <- distancia / comb
      
      escreval ("Consumo médio: ",media: 2:3)
      
      
Fimalgoritmo